---
# initially-configured user
#ansible_user:                   ubuntu
ansible_user:                   ansible
#ansible_user:                   awx
tower_create_preload_data:      false

deploy_user:                    ansible
deploy_group:                   ansible

GROUP:                          'Muppet Labs'

# by default, do not force restart of containers (needed for initial troubleshooting)
force_recreate_container:       false
# by default, do not force recreation of node mount dirs (needed for initial troubleshooting)
force_recreate_volume_dirs:     false

ansible_python_interpreter:    '/usr/bin/python3'
docker_network_name:           'nginx_proxy'
git_email:                     'services@pauljsolomon.net'
git_username:                  'Paul J Solomon'
tz:                            'America/Chicago'

#TODO:psolomon find a better solution
# global static container IPs
unbound_ip_address:            "172.16.1.50"
awx_postgres_ip_address:       "172.16.1.51"
