---
#ansible_host:        ansible.pauljsolomon.net
ansible_host:        192.168.1.194
ENV:                 PROD-LIKE
portainer_endpoint:  'http://192.168.1.187:9085/api'
nginx_awx_host:        awx-sandbox.pauljsolomon.net
