--- 
- name:          AWX Deploy
  hosts:         awx
  remote_user:   ansible
  gather_facts:  true
  become:        true

  vars_files:
    - group_vars/vault.yml

  vars:
    force_recreate_container:     true
    force_recreate_volume_dirs:   true

  roles:
    - docker
    - nginx-proxy
    - awx
