---
# run with:  ansible-playbook --vault-password-file vault-passwd-test playbooks/vault-test.yml

- name: Vault Test ONE HOST
  hosts:         deploy1
  gather_facts:  false

  vars_files:
    - group_vars/vault-test.yml

  tasks:
    # taken from regular config (group_vars/all.yml), no creds needed
    - name: test normal value
      debug: var=git_username
      run_once: true

    # taken from secret vault:  (group_vars/vault-test).yml, creds set in AWX
    - name: display test vault token
      debug:  var=secrets.test.my_new_secret
      run_once: true
