---
- name: create unbound container {{ unbound_container_name }} from {{ unbound_container_image }}
  docker_container:
    name:            '{{ unbound_container_name }}'
    image:           '{{ unbound_container_image }}'
    pull:            true
    state:           started
    # normally defaults to "false"
    recreate:        '{{ force_recreate_container }}'
    pull:            true
    restart_policy:  always
    published_ports:
      # used to test externally
      - "5353:53/tcp"
      - "5353:53/udp"
    exposed_ports:
      - "53/tcp"
      - "53/udp"
    networks:
      # subnet 172.16.1.0/24
      - name:           '{{ docker_network_name }}'
        ipv4_address:   '{{ unbound_ip_address }}'
  tags:
    - unbound
