---
- name: add awx project
  awx.awx.project:
    name:                   '{{ project_name }}'
    organization:           '{{ org_name }}'
    credential:             '{{ ssh_scm_credential_name }}'
    scm_type:               git
    scm_url:                '{{ github_repo }}'
    scm_branch:             '{{ github_branch }}'
    timeout:                20
    update_project:         false
    scm_update_on_launch:   false

    #controller_host:        '{{ awx_controller_host }}'
    controller_host:        '{{ awx_demo_url }}'
    controller_oauthtoken:  '{{ awx_access_token0 }}'
    wait:                   false
  when: not ansible_check_mode
  tags:
    - awx
    - awx_ui
