---
- name: create awx organization
  awx.awx.organization:
    name:                   '{{ org_name }}'
    #controller_host:        '{{ awx_controller_host }}'
    controller_host:        '{{ awx_demo_url }}'
    controller_oauthtoken:  '{{ awx_access_token0 }}'
  when: not ansible_check_mode
  tags:
    - awx
    - awx_ui
